name: "deploy to GitHub Pages"
on:
    pull_request:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install Packages
              run: npm ci

            - name: Fetch Origin
              run: git fetch origin master

            - name: Run Deploy
              shell: bash
              run: npm run deploy
